---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: nut
  description: Icecast on UBI9
  annotations:
    backstage.io/techdocs-ref: dir:.
    github.com/project-slug: radiorabe/container-image-icecast
  links:
    - url: https://icecast.org/
      title: Icecast Homepage
spec:
  type: container
  lifecycle: experimental
  owner: it-reaktion
  dependsOn:
    - component:default/rabe-ubi9-minimal
